### ISSUE TITLE
Create a configs other than Stylelint

### ISSUE THREAD

**Issue by dan-gamble** [standard-css/standard-css#2]
Is there merit to create configs for `scss-lint`, `postcss-sorting`, `csscomb`, etc?

**Comment by corysimmons** [comment]
We'd have to investigate if they could support our spec, but if so, yeah definitely.

**Comment by corysimmons** [comment]
Actually, I want to put all my eggs into the stylelint basket.

It seems the most powerful. I'd rather make tools for it than sacrifice rules so Standard CSS worked with weaker tools.

Hopefully stylelint will get an autocorrect feature in the near future so CSScomb doesn't have anything on it. If not, we can probably make something.

Closing for now, but if there's a lot of demand **and good reason** to support other stuff, we can revisit.
