### ISSUE TITLE
Consider Harry Roberts CSS Guidlines & Make a PostCSS Plugin Package for Standard CSS

### ISSUE THREAD

**Issue by michael-ciniawsky** [standard-css/standard-css#6]
Hi, are PR to this repo welcome? 

[CSS Guidelines](http://cssguidelin.es/)
[PostCSS Package Example](https://github.com/michael-ciniawsky/postcss-package-css/blob/master/index.js)

**Comment by dan-gamble** [comment]
They are :) But this hasn't been touched for a while i'm not sure of the current state of it!

**Comment by corysimmons** [comment]
Yeah this project is still in the womb. I'll add it to my todo list and try to get to it soon.

**Comment by michael-ciniawsky** [comment]
@corysimmons do you agree on making a plugin package which contains all nessecary plugins to write standard css ? (postcss-import, *-bem, *-sorting, *-calc, lost, autoprefixer, stylelint, stylefmt).Just a few basics to get started. If so would you mind to open a new repo were i can pull a draft of it to? like postcss-package-standard, concrete rules etc. can be added later on.

**Comment by corysimmons** [comment]
I don't think Standard CSS should tell people they have to use XYZ plugin to make their code more better. Perhaps the only exception to that rule would be Autoprefixer.

Really all I wanted Standard CSS to do was sort and space properties so all CSS would look the same. I think making it do too much would make it less modular.

In fact, Standard CSS should literally just be a stylelint.config.js file. I've just been waiting on stylelint to get some good editor support, but at this point I'm probably just going to implement this and just watch my css with the terminal or something. :(

**Comment by Arcanemagus** [comment]
@corysimmons What editor is lacking support right now?

**Comment by michael-ciniawsky** [comment]
i agree that it should not include a complete 'preprocessor' and the goal should be writting plain 'standard' css instead of preprocessor code, but plain css legs some important features like @import , which most people will not like to miss in nowadays development. But something like the 'genius intuitive senior devs sass mixins' should be avioded :).Just a few things to make the workflow smoother but as unoptiniated as possible. The [CSS Guidelines](http://cssguidelin.es/) also mentions nesting, separating styles etc.

Why not clearly seperating the different usecases ?

- standardcss-cli 
- standardcss
- postcss-package-standardcss
- stylelint-config-standardcss
- atom-standardcss
- sublime-standardcss
- brackets-standardcss

## StandardCSS 

| Preprocess                                | Linting                                                                    |
|:---------------------------------------- :|:---------------------------------------------------------------- :|
|  postcss-package-standardcss |  stylelint & stylelint-config-standradcss & stylefmt |

## Example

```js
const postcss = require('postcss')
const standardcss = require('standardcss')

const css = fs.readFileSync('style.css', 'utf-8')

const options = {
  sugarss: true/false       //  'default: false 
  preprocess: true/false  //  'default: false' disables all transformation plugins, just linting 
}

postcss(standardcss(options))
  .process(css)
  .then(result => console.log(result.css)
```

**Comment by corysimmons** [comment]
@Arcanemagus I dunno. After wrestling with Atom, Sublime, and VSCode, and all of them being insufficient, I stopped screwing with it for a few months. Which one were you in charge of? Did you get it fixed?

@michael-ciniawsky I think when I get around to this repo again I'm just going to try to mimic what Feross has done with Standard JS. If stylelint's editor plugins work then we won't need to maintain atom-standardcss, sublime-standardcss, brackets-standardcss, etc.

I don't understand what postcss-package-standardcss would do exactly since stylelint is a postcss package already and Standard CSS would just be a config for it. Same thing with the cli.

Sorry if I'm missing something. It's been a long time since I thought about stylelint/this project.

**Comment by Arcanemagus** [comment]
I work on the Atom `linter-stylelint` package :wink:

Right now the only issue open is the ability to use a locally installed version of `stylelint` instead of the bundled one (local plugins and everything work just fine, you are just limited on the version of `stylelint` used). If you find anything else broken please file an issue so it can be fixed.

**Comment by michael-ciniawsky** [comment]
> If stylelint's editor plugins work then we won't need to maintain atom-standardcss, sublime-standardcss, brackets-standardcss, etc.

@corysimmons  I agree, separate editor plugins are unnessecary/redundant.

The package would ensure the workflow (grunt/gulp/webpack) result to be StandardCSS conform. 
As this repo is a shareable, preconfigured stylelint config file for stylelint, the plugin package could be are a shareable plugin preset for PostCSS containing the 'building' plugins && config.
When you choose to write StandardCSS BEM naming and the rules for that are e.g,

```css
@component block {
    @descendent {};
    @modifier {};
}
```

```txt
Standard BEM Style Rule : block__element--modifier

// options nessecary to match the rule
postcss-bem({
    defaultNamespace: undefined
    style: 'bem',
    separators: {
        descendent: '__'
        modifier: '--'
    },
    shortcuts: {}
})
```
this is preconfigured and don't need to be set up every time.

```bash
(sudo) npm i -D grunt-postcss postcss-package-standard // done.
(sudo) npm i -D gulp-postcss postcss-package-standard // done.
(sudo) npm i -D webpack style-loader css-loader postcss-loader postcss-package-standard // done.
```
src.css, _component1.css , component2.css, ... Editor (stylelint-config-standardcss)
|
|---> Gulp/Webpack (postcss-package-standard) imports, transforms, check ?  fix(result) : minify(result)
|
|---> result.[min].css 

But as long as no concrete ruleset is finalized, this is an absolute secondary matter. When the time comes i will make one to consider usefulness.

Are there any plans when you will find time to get working on this again / suggestions for help ?

**Comment by corysimmons** [comment]
@Arcanemagus Do you know if https://github.com/AtomLinter/linter-stylelint/issues/79 ever got fixed? That bug alone made linter-stylelint completely unusable.

@michael-ciniawsky stylelint's CLI is really the only way stylelint is usable right now, and if you use a strict config (like Standard CSS aimed to be), it was impractical to switch back and forth between the terminal and the file after every keystroke. Works fine for lax configs though. Hence I halted work on this until editor linters caught up.

Once editor linters work, I'll get back to work on this project and test it in a bunch of real world situations until I'm really confident in it, then I'll revisit porting it to everything under the sun.

> Are there any plans when you will find time to get working on this again / suggestions for help ?

I dunno, let's see what @Arcanemagus says about Atom support. If Atom supports it well enough I can probably get back to work on it. If not, I'll check on it in another few months.

**Comment by Arcanemagus** [comment]
@corysimmons That specific bug was fixed in PostCSS v5.0.16, which is covered in `stylelint@^6.3.0`. `linter-stylelint` v2.8.0 includes `stylelint@6.3.3` and thus should have that particular bug fixed.

(As mentioned there, that wasn't a bug with `linter-stylelint`... it was just exposing a bug in `stylelint` that wouldn't have been easily caught by just looking at the output.)

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/15305776/4b265b10-1b93-11e6-8974-b35aec71275e.png)

**Comment by corysimmons** [comment]
Ping. Getting re-interested in launching this project. Will download stylelint docs and begin working on this again.

I browsed over this issue. Seems like we're in agreement this shouldn't be its own CLI, but rather just a config that works well with stylelint (and its integrations -- like stylefmt).

@Arcanemagus Thank you for the amazing work on Atom Linter. 💯 👍
