### ISSUE TITLE
consider stylelint & stylefmt

### ISSUE THREAD

**Issue by ungoldman** [standard-css/standard-css#7]
There's already a fairly comprehensive set of tools that I was thinking of grouping into a `standard` style interface. Looks like you almost got there. Have you thought about using these?

- [stylelint](https://github.com/stylelint/stylelint) configured with [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard)
- [stylefmt](https://github.com/morishitter/stylefmt)

These could be used as dependencies and given the following interface:

### lint

```
standard-css file
```

### format

Calls `stylelint` on target file or glob pattern with `stylelint-config-standard` and outputs any errors or issues.

```
standard-css -f style
```

Formats target file or glob pattern with `stylefmt` and outputs any errors or issues.

The objective is this approach would be to be able to include it in package.json scripts like so:

```
{
  "name": "my-cool-package",
  "devDependencies": {
    "standard": "*",
    "standard-css": "*"
  },
  "scripts": {
    "test": "standard && standard-css && node my-tests.js"
  }
}
```

Thus following the same basic usage patterns as `standard`.

**Comment by corysimmons** [comment]
Yup, this is what I want to do. tbh, I was just waiting on stylelint to get some proper editor plugin support (who wants to do strict CSS linting in terminal?).

Seems like it has some now.

I'm swamped for the next 3-5 weeks, then I can knuckle down on this.

If you need this now though, feel free to PR and I'm happy to go over it with you. 👍

**Comment by ungoldman** [comment]
I don't mind CSS linting happening in the terminal as my primary use case is standard-like vetting of pull requests for CSS-heavy projects using continuous integration (like travis-ci). If you're open to just having the above workflow for now I'd be happy to give it a try and open a PR.

**Comment by ungoldman** [comment]
Also on a side note, a lot of the standard editor plugins just require the command line interface to be present. See for example:

- https://github.com/Flet/SublimeLinter-contrib-standard
- https://github.com/ricardofbarros/linter-js-standard

So you may want to consider doing the CLI first then worrying about editor plugin support 😉

**Comment by corysimmons** [comment]
Good points.

StandardCSS would just be a wrapper around stylelint (isn't StandardJS just a wrapper around ESLint?).

I'm pretty sure the rules I was working on months ago have changed in stylelint quite a bit, but I think you get the point:
- organize everything by a group type in bigger-to-smaller importance (e.g. layout > font styles)
- newline separate these groups & alphabetically sort them for easy visual scanning
- bunch of tiny personal preferences (but I'm unsure if these should really be included - they don't add a lot of value, and in some situations could be a big PITA).

Let me know if you're interested in tackling a prototype config for it. I'd be happy to wrap it up with stylelint via meow and start taking a look at Atom plugin dev (Sublime plugin dev grosses me out a bit).

Ugh, wish I had like 2-3 solid days to devote to getting a 1.0.0 out the door... :*(

**Comment by corysimmons** [comment]
Re: A lot of editors/integrations _requiring_ Standard's CLI tool.

I don't think they do.

All those integrations and such could be accomplished with ESLint. In fact, it is probably the preferred method for a lot of people: https://github.com/feross/eslint-config-standard

I really don't want to maintain all those integrations, and I do think it's just unnecessary stylelint ecosystem fragmentation, so I'm opting for just making this a stylelint-config that people can extend in `package.json`, then just use it like:

```json
"scripts": {
    "test": "standard && stylelint src/css/**/* && node my-tests.js"
  }
```

**Comment by ungoldman** [comment]
> Re: A lot of editors/integrations *requiring* Standard's CLI tool.
> 
> I don't think they do.

I linked to a section in the standard project readme above that has links to text editor plugins, and provided two specific examples above. I don't know about the rest, but unless I am reading the documentation for each of those incorrectly, at least sublime text, atom, and brackets (and maybe vim, not sure but seems like `let g:syntastic_javascript_checkers = ['standard']` in `.vimrc` is just delegating to `standard`) most definitely do ask users to install standard locally (`npm i -g standard`) before using the plugins. I'm not sure they *should* necessarily, I was just pointing out that they do.

I understand if you want to take it in another direction. My thought process was "it would be nice for something called `standard-css` to work like `standard`" -- but CSS is not JS, and I can understand if it's not what you envisioned. Best of luck!

**Comment by corysimmons** [comment]
I feel ya. I suspect Feross just wanted to make something so you could type `standard in.js` instead of all that crazy crap we have to do nowadays with configs, webpack, and such.

We might revisit this in the future, but honestly, it'd just be an alias for something like `stylelint --config our-config.js` so I don't see a lot of value in it right this second, and it might actually make our lives a lot harder. I imagine a lot of things have stylelint support, but then we'd have to write stuff exposing standard-css on that same level.

I dunno... I'm open to it in the future if there is more community outreach for it, but in the meantime I'd just like to focus on at least getting a really well-thought-out config out there. 😨
